name: base
channels:
  - conda-forge
dependencies:
  - dask-core=2022.3.0
  - fsspec=2022.3.0
  - gcsfs=2022.3.0
  - retry=0.9.2
  - rioxarray=0.10.3
  - xarray=2022.3.0
  - zarr=2.11.3
  - python=3.9.12
